#!/usr/bin/env python3
"""Generate every publication surface from bib/publications.bib.

Writes:
  publications.qmd                  the full list, with a JSON-LD graph of every work in its head
  publications/<slug>.qmd           one page per work that has a slug (abstract, citation, full-text links,
                                    its own JSON-LD node)
  markdown/publications.md          machine-readable list

Run from the site root:  python3 scripts/generate_publications.py

Custom BibTeX fields the generator understands (see the comment block in the .bib):
  featured, slug, summary, abstract, keywords, oastatus, oaurl, license, onlineyear,
  titletrans, language, containerdoi, isbn
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bibparse  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIB = os.path.join(ROOT, "bib", "publications.bib")
SITE_URL = "https://petrspecian.com"
PERSON_ID = f"{SITE_URL}/#person"

BANNER = "<!-- GENERATED by scripts/generate_publications.py from bib/publications.bib. Do not edit by hand. -->\n"

OA_LABEL = {
    "gold": "Open access",
    "hybrid": "Open access",
    "bronze": "Free to read",
    "green": "Author manuscript available",
    "preprint": "Open access",
}

LICENSE_URL = {
    "CC BY 4.0": "https://creativecommons.org/licenses/by/4.0/",
    "CC BY-NC-ND 4.0": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    "CC BY-NC 4.0": "https://creativecommons.org/licenses/by-nc/4.0/",
}

LANG = {"czech": "cs", "slovak": "sk"}


def load():
    entries = bibparse.parse(BIB)
    for e in entries:
        e["_year"] = int(e.get("year", 0) or 0)
        if e.get("eprint") and not e.get("oastatus"):
            e["oastatus"] = "preprint"  # an arXiv record is its own open full text
    return entries


def split(entries):
    books, articles, chapters, preprints, public = [], [], [], [], []
    for e in entries:
        t = e["_type"]
        if t == "book":
            books.append(e)
        elif t == "article":
            articles.append(e)
        elif t == "incollection":
            chapters.append(e)
        elif e.get("entrysubtype") == "publicwriting":
            public.append(e)
        else:
            preprints.append(e)
    key = lambda e: -e["_year"]
    return (books, sorted(articles, key=key), sorted(chapters, key=key),
            sorted(preprints, key=key), sorted(public, key=key))


def is_free(e):
    return e.get("oastatus") in ("gold", "hybrid", "bronze", "preprint")


def fulltext(e):
    """URL of a free full text, if one is known. Prefer the explicit oaurl; an
    arXiv record is its own full text."""
    if e.get("oaurl"):
        return e["oaurl"]
    if e.get("eprint"):
        return f"https://arxiv.org/abs/{e['eprint']}"
    if is_free(e) and e.get("doi"):
        return f"https://doi.org/{e['doi']}"
    return ""


def links_for(e, from_root=True, overview=True):
    prefix = "" if from_root else "../"
    out = []
    target = bibparse.link(e)
    if target:
        out.append(f"[{bibparse.link_label(e)}]({target})")
    ft = fulltext(e)
    if ft and ft != target:
        out.append(f"[Full text]({ft})")
    if e.get("url") and e.get("doi") and e["_type"] == "book":
        out.append(f"[Publisher page]({e['url']})")
    if e.get("slug") and overview:
        out.append(f"[Overview]({prefix}publications/{e['slug']}.html)")
    return " · ".join(out)


def venue_line(e):
    if e["_type"] == "article":
        v = f"*{e.get('journal','')}*"
        if e.get("volume"):
            v += f" {e['volume']}"
        if e.get("number"):
            v += f"({e['number']})"
        if e.get("pages"):
            v += f", {e['pages']}"
        return v
    if e["_type"] == "book":
        return f"{e.get('publisher','')} · {e.get('year','')}"
    if e["_type"] == "incollection":
        return f"In *{e.get('booktitle','')}*, {e.get('publisher','')} · {e.get('year','')}"
    if e.get("eprint"):
        return f"arXiv:{e['eprint']}"
    if e.get("howpublished"):
        return f"{e['howpublished']} · {e.get('year','')}"
    return ""


def yaml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', "'").replace("\n", " ") + '"'


def page_title_parts(e):
    """Split a work's title into banner title + smaller subtitle at the first ': ' or '? '."""
    full = e["title"]
    import re as _re
    m = _re.search(r"(\?|:)\s+", full)
    if m:
        title = full[: m.end()].rstrip() if m.group(1) == "?" else full[: m.start()].strip()
        sub = full[m.end():].strip()
    else:
        title, sub = full, e.get("subtitle", "")
    return title, sub


def keywords(e):
    return [k.strip() for k in e.get("keywords", "").split(";") if k.strip()]


# ------------------------------------------------------------- JSON-LD

def schema_node(e, with_context=False):
    t = e["_type"]
    typ = {"book": "Book", "article": "ScholarlyArticle", "incollection": "Chapter"}.get(t, "ScholarlyArticle")
    if e.get("entrysubtype") == "publicwriting":
        typ = "Article"
    page = f"{SITE_URL}/publications/{e['slug']}.html" if e.get("slug") else None
    doi_url = f"https://doi.org/{e['doi']}" if e.get("doi") else None

    node = {
        "@type": typ,
        "@id": page or doi_url or e.get("url"),
        "name": e["title"],
        "headline": e["title"],
        "author": [
            ({"@type": "Person", "name": n, "@id": PERSON_ID} if n == "Petr Špecián"
             else {"@type": "Person", "name": n})
            for n in bibparse.authors(e)
        ],
        "datePublished": e.get("year"),
        "inLanguage": LANG.get(e.get("language", ""), "en"),
        "isAccessibleForFree": is_free(e),
    }
    if with_context:
        node = {"@context": "https://schema.org", **node}
    if e.get("titletrans"):
        node["alternateName"] = e["titletrans"]
    if e.get("abstract"):
        node["abstract"] = e["abstract"]
    if keywords(e):
        node["keywords"] = keywords(e)
    if e.get("license") and LICENSE_URL.get(e["license"]):
        node["license"] = LICENSE_URL[e["license"]]
    if doi_url:
        node["identifier"] = doi_url
        node["sameAs"] = doi_url
    elif e.get("url"):
        node["sameAs"] = e["url"]
    if t == "article":
        node["isPartOf"] = {"@type": "Periodical", "name": e.get("journal", "")}
        if e.get("volume"):
            node["volumeNumber"] = e["volume"]
        if e.get("number"):
            node["issueNumber"] = e["number"]
        if e.get("pages"):
            node["pagination"] = e["pages"]
    elif t == "incollection":
        node["isPartOf"] = {"@type": "Book", "name": e.get("booktitle", "")}
        if e.get("pages"):
            node["pagination"] = e["pages"]
        if e.get("publisher"):
            node["publisher"] = {"@type": "Organization", "name": e["publisher"]}
    elif t == "book":
        if e.get("publisher"):
            node["publisher"] = {"@type": "Organization", "name": e["publisher"]}
        if e.get("isbn"):
            node["isbn"] = e["isbn"]
        if e.get("subtitle"):
            node["alternativeHeadline"] = e["subtitle"]
    elif e.get("howpublished"):
        node["publisher"] = {"@type": "Organization", "name": e["howpublished"]}
    if page:
        node["url"] = page
        node["mainEntityOfPage"] = page
    ft = fulltext(e)
    if ft and ft != doi_url:
        node["encoding"] = {"@type": "MediaObject", "contentUrl": ft}
    return node


def jsonld_block(obj):
    body = json.dumps(obj, ensure_ascii=False, indent=2)
    return "<script type=\"application/ld+json\">\n" + body + "\n</script>"


def header_includes(block):
    """Indent a raw HTML block for a YAML `header-includes: |` literal."""
    return "\n".join("  " + line for line in block.split("\n"))


# ---------------------------------------------------------------- publications.qmd

def gen_list(entries):
    books, articles, chapters, preprints, public = split(entries)
    featured = [e for e in entries if e.get("featured") == "yes"]

    graph = {"@context": "https://schema.org",
             "@graph": [schema_node(e) for e in entries]}

    L = ["---",
         'title: "Publications"',
         'subtitle: "Research on AI, democracy, expertise, rationality, and institutional design"',
         'description: "Books, journal articles, chapters, preprints, and public writing by Petr Špecián, with abstracts and open-access full texts where available."',
         'pagetitle: "Publications"',
         "toc: true",
         # machine layer: alternates and the works graph live in the head, not in the body copy
         "header-includes: |",
         f'  <link rel="alternate" type="text/markdown" href="{SITE_URL}/markdown/publications.md" title="Publication list in Markdown">',
         f'  <link rel="alternate" type="application/x-bibtex" href="{SITE_URL}/bib/publications.bib" title="Publications in BibTeX">',
         header_includes(jsonld_block(graph)),
         "---", "", BANNER]

    L.append("## Selected work\n")
    L.append('::: {.selected-list}')
    for e in featured:
        kind = {"book": "Book", "article": "Journal article", "misc": "Working paper"}.get(e["_type"], "Work")
        oa = OA_LABEL.get(e.get("oastatus", ""), "")
        kicker = f"{kind} · {e.get('year','')}" + (f" · {oa}" if oa else "")
        L.append('::: {.work}')
        L.append(f'<p class="card-kicker">{kicker}</p>\n')
        if e.get("slug"):
            L.append(f"### [{e['title']}](publications/{e['slug']}.html)\n")
        else:
            L.append(f"### {e['title']}\n")
        if e.get("summary"):
            L.append(f'<p class="summary">{e["summary"]}</p>\n')
        v = venue_line(e)
        if v:
            L.append(f'<p class="publication-meta">{v}</p>\n')
        lk = links_for(e, overview=False)
        if lk:
            L.append(f'<p class="card-link">{lk}</p>')
        L.append(':::')
    L.append(':::\n')

    def section(title, items, anchor):
        if not items:
            return
        L.append(f"## {title} {{#{anchor}}}\n")
        L.append('::: {.citation-list}')
        for e in items:
            cite = bibparse.citation(e)
            extra = links_for(e)
            L.append(f"{cite} {extra}\n" if extra else f"{cite}\n")
        L.append(':::\n')

    section("Book", books, "book")
    section("Journal articles", articles, "journal-articles")
    section("Chapters", chapters, "chapters")
    section("Preprints and working papers", preprints, "preprints")
    section("Public writing", public, "public-writing")

    L.append("---\n")
    L.append("Citations for reference managers: [BibTeX](bib/publications.bib)\n")
    return "\n".join(L)


# ------------------------------------------------------------- per-paper pages

def gen_page(e):
    title, sub = page_title_parts(e)
    oa = OA_LABEL.get(e.get("oastatus", ""), "")
    desc = e.get("summary") or (e.get("abstract", "")[:220].rsplit(" ", 1)[0] + "…" if e.get("abstract") else "")

    L = ["---", f"title: {yaml_str(title)}"]
    if sub:
        L.append(f"subtitle: {yaml_str(sub)}")
    L.append(f"description: {yaml_str(desc)}")
    L.append(f"pagetitle: {yaml_str(e['title'])}")
    L.append("toc: false")
    L.append("header-includes: |")
    L.append(header_includes(jsonld_block(schema_node(e, with_context=True))))
    L.append("---\n")
    L.append(BANNER)

    meta = []
    v = venue_line(e)
    if v:
        meta.append(v)
    if e.get("onlineyear"):
        meta.append(f"first published online {e['onlineyear']}")
    if e.get("language") in LANG:
        meta.append({"cs": "In Czech", "sk": "In Slovak"}[LANG[e["language"]]])
    if oa:
        meta.append(oa)
    if e.get("license"):
        meta.append(e["license"])
    L.append(f'<p class="publication-meta">{" · ".join(m for m in meta if m.strip())}</p>\n')

    if e.get("summary"):
        L.append(f'<p class="lede">{e["summary"]}</p>\n')

    if e.get("abstract"):
        L.append("## Abstract\n")
        L.append(e["abstract"] + "\n")
        if keywords(e):
            L.append('<p class="chip-row">' + "".join(f'<span class="chip">{k}</span>' for k in keywords(e)) + "</p>\n")

    L.append("## Citation\n")
    L.append('::: {.citation-block}')
    L.append(bibparse.citation(e))
    if e.get("doi"):
        L.append(f"\n<https://doi.org/{e['doi']}>")
    L.append(':::\n')

    buttons = []
    ft = fulltext(e)
    lk = bibparse.link(e)
    if e["_type"] == "book" and e.get("url"):
        buttons.append(f"[Publisher page]({e['url']}){{.button-primary}}")
        if lk and lk != e["url"]:
            buttons.append(f"[DOI]({lk}){{.button-secondary}}")
        lk = ft = ""
    if ft:
        label = "Read the full text" if is_free(e) else "Author manuscript"
        if e.get("eprint") and not e.get("oaurl"):
            label = "Read on arXiv"
        buttons.append(f"[{label}]({ft}){{.button-primary}}")
    if lk and lk != ft:
        label = ("Volume DOI" if e.get("containerdoi")
                 else "DOI" if e["_type"] == "misc"
                 else "Publisher version (DOI)")
        cls = "button-secondary" if buttons else "button-primary"
        buttons.append(f"[{label}]({lk}){{.{cls}}}")
    if buttons:
        L.append('<p class="hero-actions">' + " ".join(buttons) + "</p>\n")

    L.append("\n[← All publications](../publications.html)\n")
    return "\n".join(L)


# ------------------------------------------------------------- markdown export

def gen_markdown(entries):
    books, articles, chapters, preprints, public = split(entries)
    L = ["# Publications: Petr Špecián", "",
         f"Canonical page: {SITE_URL}/publications.html  ",
         "ORCID: https://orcid.org/0000-0003-2702-0354  ",
         "Source of truth: bib/publications.bib  ",
         "This file is generated; do not edit by hand.  ",
         f"Abstracts and full-text links: per-work pages under {SITE_URL}/markdown/publications/ "
         f"(all of them concatenated in {SITE_URL}/llms-full.txt).", ""]

    def sect(t, items):
        if not items:
            return
        L.append(f"## {t}")
        L.append("")
        for e in items:
            line = "- " + bibparse.citation(e)
            lk = bibparse.link(e)
            if lk:
                line += f" {lk}"
            ft = fulltext(e)
            if ft and ft != lk:
                line += f" Full text: {ft}"
            if e.get("slug"):
                line += f" Details: {SITE_URL}/markdown/publications/{e['slug']}.md"
            L.append(line)
        L.append("")

    sect("Book", books)
    sect("Journal articles", articles)
    sect("Chapters", chapters)
    sect("Preprints and working papers", preprints)
    sect("Public writing", public)
    return "\n".join(L)


def main():
    entries = load()
    written = []

    def write(rel, content):
        p = os.path.join(ROOT, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            f.write(content if content.endswith("\n") else content + "\n")
        written.append(rel)

    # stale per-paper pages disappear with their bib entry
    pubdir = os.path.join(ROOT, "publications")
    keep = {f"{e['slug']}.qmd" for e in entries if e.get("slug")}
    if os.path.isdir(pubdir):
        for f in os.listdir(pubdir):
            if f.endswith(".qmd") and f not in keep:
                os.remove(os.path.join(pubdir, f))
                print("   removed stale", f)

    write("publications.qmd", gen_list(entries))
    for e in entries:
        if e.get("slug"):
            write(f"publications/{e['slug']}.qmd", gen_page(e))
    write("markdown/publications.md", gen_markdown(entries))

    print(f"{len(entries)} entries -> {len(written)} files")
    for w in written:
        print("  ", w)


if __name__ == "__main__":
    main()
